--- 
- name: "selinux disable"
  selinux:
    state: disabled
  register: st

- name: reboot if SELinux changed
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 2
  poll: 0
  ignore_errors: true
  when: st.changed

- name: waiting for server to reboot
  wait_for: host="{{ ansible_ssh_host | default(inventory_hostname) }}" port={{ ansible_ssh_port | default(22) }} search_regex=OpenSSH delay=30 timeout=180
  connection: local
  sudo: false
  when: st.changed
